export default [
	{
		id: '0',
		eqName: '路由器0',
		eqOrgId: 'eqOrgId',
		eqPortTypeNum: [
			'eqPortTypeNum/0/0/0',
			'eqPortTypeNum/0/0/1',
			'eqPortTypeNum/0/0/2',
		],
		eqTypeCode: 'router-node',
		eqTypeId: 'eqTypeId',
		eqTypeName: 'eqTypeName',
		errNode: false,
		eqIp: '192.168.1.0',
		x: 1,
		y: 0,
	},
	{
		id: '1',
		eqName: '路由器1',
		eqOrgId: 'eqOrgId',
		eqPortTypeNum: [
			'eqPortTypeNum/0/1/0',
			'eqPortTypeNum/0/1/1',
			'eqPortTypeNum/0/1/2',
		],
		eqTypeCode: 'router-node',
		eqTypeId: 'eqTypeId',
		eqTypeName: 'eqTypeName',
		errNode: false,
		eqIp: '192.168.1.1',
		x: 2,
		y: 0,
	},
	{
		id: '2',
		eqName: '路由器2',
		eqOrgId: 'eqOrgId',
		eqPortTypeNum: [
			'eqPortTypeNum/0/2/0',
			'eqPortTypeNum/0/2/1',
			'eqPortTypeNum/0/2/2',
		],
		eqTypeCode: 'router-node',
		eqTypeId: 'eqTypeId',
		eqTypeName: 'eqTypeName',
		errNode: false,
		eqIp: '192.168.1.2',
		x: 1,
		y: 1,
	},
	{
		id: '3',
		eqName: '路由器3',
		eqOrgId: 'eqOrgId',
		eqPortTypeNum: [
			'eqPortTypeNum/3/1/0',
			'eqPortTypeNum/3/1/1',
			'eqPortTypeNum/3/1/2',
		],
		eqTypeCode: 'router-node',
		eqTypeId: 'eqTypeId',
		eqTypeName: 'eqTypeName',
		errNode: false,
		eqIp: '192.168.1.2',
		x: 2,
		y: 1,
	},
	{
		id: '4',
		eqName: '交换机1',
		eqOrgId: 'eqOrgId',
		eqPortTypeNum: [
			'eqPortTypeNum/4/1/0',
			'eqPortTypeNum/4/1/1',
			'eqPortTypeNum/4/1/2',
		],
		eqTypeCode: 'router-node',
		eqTypeId: 'eqTypeId',
		eqTypeName: 'eqTypeName',
		errNode: false,
		eqIp: '192.168.1.2',
		x: 1,
		y: 2,
	},
	{
		id: '5',
		eqName: '交换机2',
		eqOrgId: 'eqOrgId',
		eqPortTypeNum: [
			'eqPortTypeNum/5/1/0',
			'eqPortTypeNum/5/1/1',
			'eqPortTypeNum/5/1/2',
		],
		eqTypeCode: 'router-node',
		eqTypeId: 'eqTypeId',
		eqTypeName: 'eqTypeName',
		errNode: false,
		eqIp: '192.168.1.2',
		x: 2,
		y: 2,
	},
	{
		id: '6',
		eqName: '防火墙1',
		eqOrgId: 'eqOrgId',
		eqPortTypeNum: [
			'eqPortTypeNum/6/1/0',
			'eqPortTypeNum/6/1/1',
			'eqPortTypeNum/6/1/2',
		],
		eqTypeCode: 'router-node',
		eqTypeId: 'eqTypeId',
		eqTypeName: 'eqTypeName',
		errNode: false,
		eqIp: '192.168.1.2',
		x: 0,
		y: 2,
	},
	{
		id: '7',
		eqName: '防火墙2',
		eqOrgId: 'eqOrgId',
		eqPortTypeNum: [
			'eqPortTypeNum/0/7/0',
			'eqPortTypeNum/0/7/1',
			'eqPortTypeNum/0/7/2',
		],
		eqTypeCode: 'router-node',
		eqTypeId: 'eqTypeId',
		eqTypeName: 'eqTypeName',
		errNode: false,
		eqIp: '192.168.1.2',
		x: 3,
		y: 2,
	},
]
